FROM debian:10

RUN apt-get update \
    && apt-get install -y libncurses5-dev \
					   libgtk2.0-dev \
					   libatk1.0-dev \
					   libcairo2-dev \
					   libx11-dev \
					   libxpm-dev \
					   libxt-dev \
					   python3-dev \
					   ruby-dev \
					   lua5.1 \
					   lua5.1-dev \
					   libperl-dev \
					   git \
	&& git clone https://github.com/vim/vim.git \
	&& cd vim \
	&& ./configure --with-features=huge \
    --enable-multibyte \
    --enable-rubyinterp=yes \
    --enable-pythoninterp=yes \
    --enable-python3interp=yes \
    --with-python3-config-dir=/usr/lib/python3.5/config \
    --enable-perlinterp=yes \
    --enable-luainterp=yes \
    --enable-gui=gtk2 --enable-cscope --prefix=/usr \
	&& make \
	&& make install\
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* 

